### ISSUE TITLE
Getting Javascript Error while copying dashboard

### ISSUE THREAD

**Issue by udyan123** [Appdynamics/FastAppConfig#5]
A JavaScript error occurred in the main process

Uncaught Exception:
AssertionError: obj needs to be an object
    at JSONPath.apply (/Users/xxxx/FastAppConfig/node_modules/jsonpath/lib/index.js:32:10)
    at Object.exports.updateDashboard (/Users/xxxx/FastAppConfig/src/AppConfigManager.js:26:17)
    at /Users/xxxx/FastAppConfig/src/AppConfigManager.js:130:30
    at /Users/xxxx/FastAppConfig/src/AppConfigManager.js:74:3
    at /Users/xxxx/FastAppConfig/src/RestManager.js:295:4
    at IncomingMessage.<anonymous> (/Users/xxxx/FastAppConfig/src/RestManager.js:74:5)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)

Request you to help me on this issue

**Comment by rijincp** [comment]
Hi @udyan123 please provide the following to help us troubleshoot.
1) What's the commit you are on? Run: git log -1 
2) What version of node are you using? node --version
3) Make sure you have done a npm install 
4) How can we reproduce the error. 
Thanks

**Comment by jdbarfield** [comment]
Hi @udyan123,

Can you also select the following:

1. Controller URL
2. Controller version
3. Dashboard name and theme

Thanks!

**Comment by richpaul1** [comment]
Yes, this seems like it cannot communicate with the controller. 

1. Can you change the username and password in your config.json file and send us the contents please.
2. Let us know if you are using SAML Authentication also.

**Comment by udyan123** [comment]
Hi

I am able to connect to controller. Even I can see my applications. But
while copying dashboard in step 4 I am getting this error.

Regards
Udyan

**Comment by jdbarfield** [comment]
Hi @udyan123 ,

Are you using the "Health Rules and Dashboard Templates" link, or the "Sample Dashboards" link?

If you are using the "Health Rules and Dashboard Templates" link, please try the "Sample Dashboards" link and let us know if you see the same problem.

Thanks
James

**Comment by richpaul1** [comment]
@udyan123 

Also send us the templates element from your config.json file. 

This needs to be configured to point to an existing application and dashboard that exists in your controller. 

The idea is that in your controller you have decided that the Health Rules and Dashboard that has been configured for an application is the main template for other applications.

"templates":[
        {"id":1,"name":"Java Template","type":"Java","description":"Java Application - Health Rules and Dashboards","appid":2,"dashid":2},
        {"id":2,"name":".NET Template","type":".NET","description":".NET Application - Health Rules and Dashboards","appid":3,"dashid":3}
    ]

Is just a sample of how to configure it, you then need to update appid to the value of your application id which you can get from the url in the controller when you navigate to your application dashboard that shows you the flowmap etc.. Then update the dashid to the custom dashboard id you created which is associated to your template application. You can get this dashboard id from the url when you view your custom dashboard.

When you step through the wizard, You pick which template from this list, then you select the target application you want to copy to, then you copy the health rules from your template application, and last you copy the dashboard from your template application. This downloads the data from your controller i.e. health rules and dashboard and updates the application references and pushes it back to your controller. Nothing is stored in FastAppConfig.

If you want to just deploy our sample of Dashboards then use "Sample Dashboards" Feature instead, as @jdbarfield suggests.

Soon, we will post some videos online that will make this a little easier to understand.

**Comment by udyan123** [comment]
Hi James,

I was using Health Rules and Dashboard Templates last day and trying to
copying dashboards.

Thanks for your response.

Today, I am able to deploy Sample dashboards. But I don't see health rules
getting copied via Health Rules and dashboard templates.

Regards
Udyan

**Comment by udyan123** [comment]
Hi James,

Please find excerpts from json file

 "https" : true,
    "templates":[
        {"id":1,"name":"Java Template","type":"Java","description":"Java
Application - Health Rules and Dashboards","appid":2,"dashid":2},
        {"id":2,"name":".NET Template","type":".NET","description":".NET
Application - Health Rules and Dashboards","appid":2712,”dashid”:1693}
    ]
}

But now after changing the appid and dashid, I am getting JS error:

Uncaught Exception:

SyntaxError: /Users/udyan123/FastAppConfig/config.json: Unexpected token ”
in JSON at position 441

    at Object.Module._extensions..json (module.js:573:27)

    at Module.load (module.js:473:32)

    at tryModuleLoad (module.js:432:12)

    at Function.Module._load (module.js:424:3)

    at Module.require (module.js:483:17)

    at require (internal/module.js:20:19)

    at Object.<anonymous>
(/Users/udyan123/FastAppConfig/src/ConfigManager.js:8:18)

    at Module._compile (module.js:556:32)

    at Object.Module._extensions..js (module.js:565:10)

    at Module.load (module.js:473:32)
Even when I am reverting back to the old values, the application is giving
the above error.

Regards
Udyan
