### ISSUE TITLE
Dashboard Wizard not working

### ISSUE THREAD

**Issue by udyan123** [Appdynamics/FastAppConfig#9]
While selecting Dashboard wizard, its giving error:

[2017-02-18 03:08:01.183] [ERROR] app - Something went wrong: { Error: Failed to lookup view "dashboardWizard" in views directory "C:\Users\udyan123\FastAppConfig\views"
    at Function.app.render (C:\Users\udyan123\FastAppConfig\node_modules\express\lib\application.js:516:17)
    at ServerResponse.res.render (C:\Users\udyan123\FastAppConfig\node_modules\express\lib\response.js:900:7)
    at C:\Users\udyan123\FastAppConfig\app.js:93:9
    at Layer.handle [as handle_request] (C:\Users\udyan123\FastAppConfig\node_modules\express\lib\router\layer.js:82:5)
    at next (C:\Users\udyan123\FastAppConfig\node_modules\express\lib\router\route.js:100:13)
    at Route.dispatch (C:\Users\udyan123\FastAppConfig\node_modules\express\lib\router\route.js:81:3)
    at Layer.handle [as handle_request] (C:\Users\udyan123\FastAppConfig\node_modules\express\lib\router\layer.js:82:5)
    at C:\Users\udyan123\FastAppConfig\node_modules\express\lib\router\index.js:234:24
    at Function.proto.process_params (C:\Users\udyan123\FastAppConfig\node_modules\express\lib\router\index.js:312:12)
    at C:\Users\udyan123\FastAppConfig\node_modules\express\lib\router\index.js:228:12
  view:
   View {
     name: 'dashboardWizard',
     root: 'C:\\Users\\udyan123\\FastAppConfig\\views',
     defaultEngine: 'ejs',
     ext: '.ejs',
     engine: [Function],
     path: undefined } }

**Comment by jdbarfield** [comment]
Hello,

There was a file missing from the last commit. Please get latest and try again.

Thanks!

**Comment by udyan123** [comment]
Hi jdbarfield,

Yes it's working now.

Regards
Udyan
